# SPDX-License-Identifier: GPL-2.0
#
# Makefile for linux/drivers/platform/x86/amd-apml
# AMD APML BMC interface drivers
#


apml_sbrmi-objs = sbrmi.o sbrmi-common.o
obj-$(CONFIG_APML_SBRMI)	+= apml_sbrmi.o
obj-$(CONFIG_APML_SBTSI)	+= apml_sbtsi.o
