#
# Makefile for the ASPEED drivers.
#

obj-$(CONFIG_AST_VIDEO)		+= ast_video.o
obj-$(CONFIG_AST_LPC)           += ast-lpc.o ast-lpc_plus.o
obj-$(CONFIG_AST_PECI)          += ast_peci.o
obj-$(CONFIG_AST_MBX)           += ast_mailbox.o
obj-$(CONFIG_AST_JTAG)          += ast_jtag.o
obj-$(CONFIG_AST_MCTP)          += ast_mctp.o
obj-$(CONFIG_AST_XDMA)          += ast_xdma.o
obj-$(CONFIG_AST_ESPI)          += ast_espi.o

