#
# Makefile for the PECI core and bus drivers.
#

# Core functionality
obj-$(CONFIG_PECI)		+= peci-core.o
obj-$(CONFIG_PECI_CHARDEV)	+= peci-dev.o

# Hardware specific bus drivers
obj-$(CONFIG_PECI_ASPEED)	+= peci-aspeed.o
