#
# Makefile for the ASPEED drivers.
#

obj-$(CONFIG_AST_VIDEO)		+= ast_video.o
obj-$(CONFIG_ADC_CAT9883)	+= adc_cat9883.o
obj-$(CONFIG_AST_KCS)		+= ast_kcs.o
obj-$(CONFIG_AST_GPIO) 		+= ast_gpio.o
obj-$(CONFIG_AST_SPI_BIOS) 	+= ast_spi_bios.o
obj-$(CONFIG_AST_PECI)		+= ast_peci.o
